appname         = adapi
httpport        = 8090
runmode         = dev
autorender      = false
copyrequestbody = true
EnableDocs      = true
logpath         = logs
access_control_allow_origin = *
dbconnect       = root:123456@tcp(10.1.9.164:3307)/plugin
cache_time      = 60
fabricate_plugin= 4167633929
weburl          = up.filmkaynagi.com
jsurl           = /js/
